import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserProvider from "@/providers/UserProvider";
import { Toaster } from "react-hot-toast";
import MiniSidebar from "@/components/MiniSidebar/MiniSidebar";
import Header from "@/components/Header/Header";
import MainContentLayout from "@/providers/MainContentLayout";
import SidebarProvider from "@/providers/SidebarProvider";
import MainLayout from "@/providers/MainLayout";


const inter = Inter({
    subsets: ["latin"]
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <UserProvider>
                    <Toaster position="top-center" />
                    <div className="grid grid-cols-[auto_1fr] h-[100vh]">
                        <MiniSidebar />
                        <div className="h-[100vh]">
                            <Header />
                            <MainContentLayout>
                                <MainLayout>{children}</MainLayout>
                                <SidebarProvider />
                            </MainContentLayout>
                        </div>
                    </div>
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
